spring:
  application:
    name: gateway-server
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**
              filters:
                - StripPrefix=1

            - id: record-service
              uri: lb://record-service
              predicates:
                - Path=/records/**
              filters:
                - StripPrefix=1

            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/notifications/**
              filters:
                - StripPrefix=1

            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/payments/**
              filters:
                - StripPrefix=1

            - id: place-service
              uri: lb://place-service
              predicates:
                - Path=/places/**
              filters:
                - StripPrefix=1

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/orders/**
              filters:
                - StripPrefix=1

            - id: matching-service
              uri: lb://matching-service
              predicates:
                - Path=/matchings/**
              filters:
                - StripPrefix=1

            - id: plan-service
              uri: lb://plan-service
              predicates:
                - Path=/plans/**
              filters:
                - StripPrefix=1

            - id: company-service
              uri: lb://company-service
              predicates:
                - Path=/companies/**
              filters:
                - StripPrefix=1

jwt:
  secret: ${JWT_SECRET}

