spring:
  application:
    name: gateway-server
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      server:
        webflux:
          default-filters:
            - name: Retry
              args:
                retries: 3
                methods: GET
                statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms
                  factor: 2
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**, /auth/**

            - id: record-service
              uri: lb://record-service
              predicates:
                - Path=/records/**

            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/notifications/**

            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/payments/**

            - id: place-service
              uri: lb://place-service
              predicates:
                - Path=/places/**

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/orders/**

            - id: matching-service
              uri: lb://matching-service
              predicates:
                - Path=/matchings/**

            - id: plan-service
              uri: lb://plan-service
              predicates:
                - Path=/plans/**

            - id: company-service
              uri: lb://company-service
              predicates:
                - Path=/companies/**

# whitelist
gateway:
  whitelist:
    - /users/signup
    - /auth/login
    - /auth/refresh

# jwt
jwt:
  secret: ${JWT_SECRET}

