spring:
  application:
    name: gateway-server
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      server:
        webflux:
          default-filters:
            - name: Retry
              args:
                retries: 3
                methods: GET
                statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms
                  factor: 2
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**, /auth/**
            - id: record-service
              uri: lb://record-service
              predicates:
                - Path=/feeds/**
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/notifications/**
            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/payments/**
            - id: place-service
              uri: lb://place-service
              predicates:
                - Path=/places/**
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/orders/**
            - id: matching-service
              uri: lb://matching-service
              predicates:
                - Path=/matching/**, /user-settings/**
            - id: plan-service
              uri: lb://plan-service
              predicates:
                - Path=/plans/**
            - id: company-service
              uri: lb://company-service
              predicates:
                - Path=/companies/**, /products/**

server:
  port: 8080

eureka:
  client:
    service-url:
#      defaultZone: ${EUREKA_SERVER_URL:https://dolphin-device-evident.ngrok-free.dev/eureka}
       defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}

#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_SERVER_URL:https://dolphin-device-evident.ngrok-free.dev/eureka}
#      #defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: pelvis-pounce-attempt.ngrok-free.dev
#    non-secure-port: 80
#    prefer-ip-address: false

gateway:
  whitelist:
    - /users/signup
    - /auth/login
    - /auth/refresh
    - /internal/**

jwt:
  secret: ${JWT_SECRET}